# Generated by Django 3.1.7 on 2021-02-23 19:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('surrogate_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('current_flag', models.BooleanField(default=True)),
                ('period_from', models.DateTimeField(default=datetime.datetime(2021, 2, 23, 21, 27, 53, 820104))),
                ('period_to', models.DateTimeField(null=True)),
                ('customer_key', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'orders_customer',
            },
        ),
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('surrogate_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('current_flag', models.BooleanField(default=True)),
                ('period_from', models.DateTimeField(default=datetime.datetime(2021, 2, 23, 21, 27, 53, 820104))),
                ('period_to', models.DateTimeField(null=True)),
                ('zip_code', models.CharField(max_length=10)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('city', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=2, null=True)),
            ],
            options={
                'db_table': 'orders_geolocation',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'orders_order_status',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'orders_payment_method',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('surrogate_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('current_flag', models.BooleanField(default=True)),
                ('period_from', models.DateTimeField(default=datetime.datetime(2021, 2, 23, 21, 27, 53, 820104))),
                ('period_to', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('translated_name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'orders_product_category',
            },
        ),
        migrations.CreateModel(
            name='StageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category_name', models.CharField(max_length=255, null=True)),
                ('product_category_name_english', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'orders_stage_category',
            },
        ),
        migrations.CreateModel(
            name='StageCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=255, null=True)),
                ('customer_unique_id', models.CharField(max_length=255, null=True)),
                ('customer_zip_code_prefix', models.CharField(max_length=10)),
                ('customer_city', models.CharField(max_length=255, null=True)),
                ('customer_state', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'orders_stage_customer',
            },
        ),
        migrations.CreateModel(
            name='StageGeolocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geolocation_zip_code_prefix', models.CharField(max_length=10, null=True)),
                ('geolocation_lat', models.FloatField(null=True)),
                ('geolocation_lng', models.FloatField(null=True)),
                ('geolocation_city', models.CharField(max_length=255, null=True)),
                ('geolocation_state', models.CharField(max_length=2, null=True)),
            ],
            options={
                'db_table': 'orders_stage_geolocation',
            },
        ),
        migrations.CreateModel(
            name='StageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255)),
                ('order_item_id', models.IntegerField(null=True)),
                ('product_id', models.CharField(max_length=255)),
                ('seller_id', models.CharField(max_length=255)),
                ('shipping_limit_date', models.DateTimeField(null=True)),
                ('price', models.FloatField(null=True)),
                ('freight_value', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'orders_stage_item',
            },
        ),
        migrations.CreateModel(
            name='StageOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, null=True)),
                ('customer_id', models.CharField(max_length=255, null=True)),
                ('order_status', models.CharField(max_length=255, null=True)),
                ('order_purchase_timestamp', models.DateTimeField(null=True)),
                ('order_approved_at', models.DateTimeField(null=True)),
                ('order_delivered_carrier_date', models.DateTimeField(null=True)),
                ('order_delivered_customer_date', models.DateTimeField(null=True)),
                ('order_estimated_delivery_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'orders_stage_order',
            },
        ),
        migrations.CreateModel(
            name='StagePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, null=True)),
                ('payment_sequential', models.IntegerField(null=True)),
                ('payment_type', models.CharField(max_length=255, null=True)),
                ('payment_installments', models.IntegerField(null=True)),
                ('payment_value', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'orders_stage_payment',
            },
        ),
        migrations.CreateModel(
            name='StageProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255, null=True)),
                ('product_category_name', models.CharField(max_length=255, null=True)),
                ('product_name_lenght', models.IntegerField(null=True)),
                ('product_description_lenght', models.IntegerField(null=True)),
                ('product_photos_qty', models.IntegerField(null=True)),
                ('product_weight_g', models.FloatField(null=True)),
                ('product_length_cm', models.FloatField(null=True)),
                ('product_height_cm', models.FloatField(null=True)),
                ('product_width_cm', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'orders_stage_product',
            },
        ),
        migrations.CreateModel(
            name='StageSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=255, null=True)),
                ('seller_zip_code_prefix', models.CharField(max_length=10, null=True)),
                ('seller_city', models.CharField(max_length=255, null=True)),
                ('seller_state', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'orders_stage_seller',
            },
        ),
        migrations.CreateModel(
            name='ShippingDetail',
            fields=[
                ('surrogate_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('current_flag', models.BooleanField(default=True)),
                ('period_from', models.DateTimeField(default=datetime.datetime(2021, 2, 23, 21, 27, 53, 820104))),
                ('period_to', models.DateTimeField(null=True)),
                ('freight_value', models.FloatField()),
                ('shipping_lim_date', models.DateTimeField()),
                ('purchased_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField(null=True)),
                ('delivered_carrier', models.DateTimeField(null=True)),
                ('delivered_customer', models.DateTimeField(null=True)),
                ('estimated_delivery', models.DateTimeField()),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.orderstatus')),
            ],
            options={
                'db_table': 'orders_shipping_detail',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('surrogate_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('current_flag', models.BooleanField(default=True)),
                ('period_from', models.DateTimeField(default=datetime.datetime(2021, 2, 23, 21, 27, 53, 820104))),
                ('period_to', models.DateTimeField(null=True)),
                ('seller_key', models.CharField(max_length=255)),
                ('geolocation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.geolocation')),
            ],
            options={
                'db_table': 'orders_seller',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('surrogate_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('current_flag', models.BooleanField(default=True)),
                ('period_from', models.DateTimeField(default=datetime.datetime(2021, 2, 23, 21, 27, 53, 820104))),
                ('period_to', models.DateTimeField(null=True)),
                ('product_key', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('weight', models.FloatField(null=True)),
                ('length', models.FloatField(null=True)),
                ('height', models.FloatField(null=True)),
                ('width', models.FloatField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.productcategory')),
            ],
            options={
                'db_table': 'orders_product',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('surrogate_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('current_flag', models.BooleanField(default=True)),
                ('period_from', models.DateTimeField(default=datetime.datetime(2021, 2, 23, 21, 27, 53, 820104))),
                ('period_to', models.DateTimeField(null=True)),
                ('order_key', models.CharField(max_length=255)),
                ('n_items', models.IntegerField(null=True)),
                ('payment_value', models.FloatField()),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.paymentmethod')),
                ('shipping_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.shippingdetail')),
            ],
            options={
                'db_table': 'orders_order_detail',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.customer')),
                ('detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.orderdetail')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.product')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.seller')),
            ],
            options={
                'db_table': 'orders_order',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='geolocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.geolocation'),
        ),
    ]
