# Generated by Django 3.1.7 on 2021-02-23 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='period_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 0, 28, 24, 558457)),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='period_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 0, 28, 24, 558457)),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='period_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 0, 28, 24, 558457)),
        ),
        migrations.AlterField(
            model_name='product',
            name='period_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 0, 28, 24, 558457)),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='period_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 0, 28, 24, 558457)),
        ),
        migrations.AlterField(
            model_name='seller',
            name='period_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 0, 28, 24, 558457)),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='period_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 0, 28, 24, 558457)),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('id', 'current_flag')},
        ),
        migrations.AlterUniqueTogether(
            name='geolocation',
            unique_together={('id', 'current_flag')},
        ),
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together={('id', 'current_flag')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('id', 'current_flag')},
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('id', 'current_flag')},
        ),
        migrations.AlterUniqueTogether(
            name='seller',
            unique_together={('id', 'current_flag')},
        ),
        migrations.AlterUniqueTogether(
            name='shippingdetail',
            unique_together={('id', 'current_flag')},
        ),
    ]
